name: software
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # 基础依赖
  - flask=2.3.*
  - flask-sqlalchemy=3.1.*
  - flask-cors=4.0.*
  - psycopg2=2.9.*
  - requests=2.31.*
  - python-dotenv==1.0.0

  # 手势识别依赖
  - opencv=4.9.*
  - numpy=1.23.5
  - pip=24.0
  - pip:
    - mediapipe==0.10.9
    - protobuf==3.20.3
    - pyautogui==0.9.54
    - tensorflow
    - tensorflow-hub
    - pyjwt
    - PyYAML
    - pyaudio
    - funasr
    - gevent
    - gevent-websocket
    - flask_sock
    - pvporcupine